### ISSUE TITLE
Is auto-dock device available?

### ISSUE THREAD

**Issue by k-okada** [fetchrobotics/fetch_msgs#6]
Hi,

I'm very interestedin auto-docking station for a fetch robot, is it on sale? if not when do you plan shipping?

**Comment by mikeferguson** [comment]
Yes, the dock is available, our sales team has reached out to you directly.

**Comment by k-okada** [comment]
great! thank you

--
◉ Kei Okada


2016-09-22 13:12 GMT+09:00 Michael Ferguson <notifications@github.com>:
