### ISSUE TITLE
ros-indigo-fetch-auto-dock not found

### ISSUE THREAD

**Issue by kmotohas** [fetchrobotics/fetch_msgs#9]
I want to use the auto docking following the tutorial.
http://docs.fetchrobotics.com/docking.html

But I do not find `ros-indigo-fetch-auto-dock` on the apt repository so the auto docking action server cannot be brought up.
Where is this package now?

Thanks

**Comment by mikeferguson** [comment]
This package is not open source, and thus is not hosted on packages.ros.org -- you'll need to make sure you have added packages.fetchrobotics.com to your APT sources: http://docs.fetchrobotics.com/care_and_feeding.html#re-setting-up-apt-get-sources

**Comment by moriarty** [comment]
FYI. We've now Open Sourced a version of fetch-auto-dock as fetch-open-auto-dock.

https://github.com/fetchrobotics/fetch_open_auto_dock

**Comment by kmotohas** [comment]
Thanks! I'll look into it.

**Comment by moriarty** [comment]
I'm closing this, the package is available on the public pacakges.ros.org in melodic as `ros-melodic-fetch-open-auto-dock`.
For indigo, it's hosted on our packages site as pointed out above.
